# This file was generated by GoReleaser. DO NOT EDIT.
cask "fotingo" do
  name "fotingo"
  desc "CLI to streamline workflows across Git, GitHub, and Jira."
  homepage "https://github.com/tagoro9/fotingo"
  version "5.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fotingo"

  on_macos do
    on_intel do
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_darwin_amd64.tar.gz"
      sha256 "aaffd69564cc0061c078fbef972bff4d6aaec88e6287031e02b07f2d2311d741"
    end
    on_arm do
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_darwin_arm64.tar.gz"
      sha256 "e67b46c9b8b88aabc6a90e55f95afd6f4b3b78af9b9651abd95d85f314e87152"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_linux_amd64.tar.gz"
      sha256 "21925cbba139eb13d58ca2df38a6c44b3bb6cd7fb4bc2294a3b60e98cfaf125c"
    end
    on_arm do
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_linux_arm64.tar.gz"
      sha256 "1d4633089a5b6ded1b654edc5c73c0aa3c794e21dff4f22496f9f6350f5b8a87"
    end
  end

  # No zap stanza required
end
