# This file was generated by GoReleaser. DO NOT EDIT.
cask "fotingo" do
  version "5.7.0"

  on_macos do
    on_arm do
      sha256 "9be13f7e749cdc8c852761301aa0178e659aba61ab733660318905ada3b5f8f8"
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1825121da44d3bdc8cd7856b46084138984c0d91d8c4ce6331486bb5303f9c2"
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ade0775202621c43829c15b208b00e0ee021a3fcab419a5eb4266245baf32297"
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d3d99625c08e06d12f3538583a1773b5712ce5af722ac80832012ad67d587ce"
      url "https://github.com/tagoro9/fotingo/releases/download/v#{version}/fotingo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fotingo"
  desc "CLI to streamline workflows across Git, GitHub, and Jira."
  homepage "https://github.com/tagoro9/fotingo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fotingo"

  # No zap stanza required
end
